import React from 'react';
import { Eye, EyeOff, Info, ShieldAlert } from 'lucide-react';
import type { AppState, ClassAssessment, ModelId, ProblemType } from '../types';
import { MODEL_OPTIONS } from '../types';
import { Button, Card, SectionLabel } from './Common';

interface Props {
  state: AppState;
  setState: React.Dispatch<React.SetStateAction<AppState>>;
  onGenerate: () => void;
  error: string | null;
}

const DISCLOSURE_TEXT = [
  {
    heading: 'API Key Responsibility',
    body: 'You are using your own Anthropic API key. You are solely responsible for any usage costs incurred. VeriQAI recommends creating a dedicated key with a spending limit at console.anthropic.com before use.',
  },
  {
    heading: 'AI-Generated Content',
    body: 'All problem descriptions, solutions, templates, and test cases are generated by an AI model. You are responsible for reviewing and verifying all generated content before use in any assessment or educational context.',
  },
  {
    heading: 'No Warranty',
    body: 'This tool is provided "as is" under the MIT licence, without warranty of any kind. VeriQAI accepts no liability for inaccurate, incomplete, or harmful generated content.',
  },
  {
    heading: 'Trademark Notice',
    body: 'MATLAB and MATLAB Grader are trademarks of The MathWorks, Inc. This tool is not affiliated with or endorsed by MathWorks.',
  },
];

const Stage0Input: React.FC<Props> = ({ state, setState, onGenerate, error }) => {
  const {
    apiKey, showApiKey, model, objective, numOptions, problemType, classAssessment, disclosureAccepted,
  } = state;

  const set = <K extends keyof AppState>(key: K, value: AppState[K]) =>
    setState(s => ({ ...s, [key]: value }));

  const canGenerate = apiKey.trim() !== '' && objective.trim() !== '' && disclosureAccepted;

  const ptHelp: Record<ProblemType, string> = {
    Script:         'Student submits a .m script. Variables are assessed in the workspace.',
    Function:       'Student submits a .m function. Inputs/outputs are assessed directly.',
    Class:          'Student submits a classdef .m file. Properties and methods are assessed via instantiation.',
    'Object usage': 'Student writes a script that creates and processes an array of objects. A complete supporting class is generated and provided as a read-only file.',
  };

  const CLASS_ASSESSMENTS: { value: ClassAssessment; blankDesc: string }[] = [
    { value: 'Constructor — property assignment', blankDesc: 'Constructor body lines' },
    { value: 'Constructor — computed property',   blankDesc: 'Derived property line only' },
    { value: 'Instance method',                   blankDesc: 'Method body' },
    { value: 'Constant property',                 blankDesc: 'Value in properties (Constant) block' },
    { value: 'Operator overloading',              blankDesc: 'Overloaded operator method body' },
  ];

  return (
    <div className="space-y-6 max-w-2xl mx-auto">
      <div className="text-center pb-2">
        <h2 className="text-2xl font-bold text-brand-dark">Generate MATLAB Grader Problems</h2>
        <p className="text-gray-500 text-sm mt-1">
          Provide a learning objective and let Claude generate ready-to-use problem artifacts.
        </p>
      </div>

      {/* API Key */}
      <Card className="p-5 space-y-4">
        <div>
          <SectionLabel>Anthropic API Key</SectionLabel>
          <div className="relative">
            <input
              type={showApiKey ? 'text' : 'password'}
              value={apiKey}
              onChange={e => set('apiKey', e.target.value)}
              placeholder="sk-ant-api03-..."
              className="w-full font-mono text-sm border border-gray-300 rounded-md px-3 py-2 pr-20
                         focus:outline-none focus:ring-2 focus:ring-brand-accent focus:border-transparent"
            />
            <button
              type="button"
              onClick={() => set('showApiKey', !showApiKey)}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 flex items-center gap-1 text-xs"
            >
              {showApiKey ? <EyeOff size={14} /> : <Eye size={14} />}
              {showApiKey ? 'Hide' : 'Show'}
            </button>
          </div>
        </div>

        {/* Advisory */}
        <div className="flex items-start gap-2 bg-blue-50 border border-blue-200 rounded-md p-3 text-xs text-blue-800">
          <Info size={14} className="flex-shrink-0 mt-0.5 text-blue-500" />
          <div className="space-y-1.5">
            <p>
              Your API key is used only in this browser session. It is never stored, logged, or
              transmitted except directly to <strong>api.anthropic.com</strong>.{' '}
              Sign up, purchase API credits, and create a dedicated key with a spending limit at{' '}
              <a
                href="https://console.anthropic.com"
                target="_blank"
                rel="noopener noreferrer"
                className="underline font-medium"
              >
                console.anthropic.com
              </a>.
            </p>
            <p className="text-blue-700">
              <strong>💡 Typical cost:</strong> Generating and fully developing 4 problems
              (approx. 20 API calls) costs around <strong>$0.05–$0.10</strong> with Claude
              Sonnet 4.6. A <strong>$5 spending limit</strong> is more than enough for
              extensive use.
            </p>
          </div>
        </div>
      </Card>

      {/* Model */}
      <Card className="p-5">
        <SectionLabel>Claude Model</SectionLabel>
        <select
          value={model}
          onChange={e => set('model', e.target.value as ModelId)}
          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm
                     focus:outline-none focus:ring-2 focus:ring-brand-accent bg-white"
        >
          {MODEL_OPTIONS.map(opt => (
            <option key={opt.value} value={opt.value}>{opt.label}</option>
          ))}
        </select>
      </Card>

      {/* Learning Objective */}
      <Card className="p-5">
        <SectionLabel>Learning Objective</SectionLabel>
        <textarea
          value={objective}
          onChange={e => set('objective', e.target.value)}
          rows={4}
          placeholder={`e.g.\nLogical Scalars and Variables\n- Learning objective: Create and manipulate logical scalars; understand true/false types.`}
          className="w-full border border-gray-300 rounded-md px-3 py-2 text-sm resize-none
                     focus:outline-none focus:ring-2 focus:ring-brand-accent"
        />
      </Card>

      {/* Problem Type + Number of Options */}
      <Card className="p-5 space-y-4">
        <fieldset>
          <legend className="text-sm font-semibold text-gray-700 mb-3">
            MATLAB Grader Problem Type
          </legend>
          <div className="flex gap-6">
            {(['Script', 'Function', 'Class', 'Object usage'] as ProblemType[]).map(pt => (
              <label key={pt} className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  name="problemType"
                  value={pt}
                  checked={problemType === pt}
                  onChange={() => set('problemType', pt)}
                  className="accent-brand-accent"
                />
                <span className="text-sm font-medium text-gray-700">{pt}</span>
              </label>
            ))}
          </div>
          <p className="mt-2 text-xs text-gray-500">{ptHelp[problemType]}</p>

          {problemType === 'Class' && (
            <div className="mt-4 border-t border-gray-100 pt-4">
              <SectionLabel>What is being assessed?</SectionLabel>
              <div className="overflow-hidden rounded-md border border-gray-200">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="text-left px-3 py-2 font-semibold text-gray-600 w-1/2">Option</th>
                      <th className="text-left px-3 py-2 font-semibold text-gray-600 w-1/2">What gets blanked in template</th>
                    </tr>
                  </thead>
                  <tbody>
                    {CLASS_ASSESSMENTS.map(({ value, blankDesc }, i) => (
                      <tr
                        key={value}
                        className={`cursor-pointer transition-colors ${
                          classAssessment === value
                            ? 'bg-brand-accent/10 border-l-2 border-brand-accent'
                            : 'hover:bg-gray-50 border-l-2 border-transparent'
                        } ${i < CLASS_ASSESSMENTS.length - 1 ? 'border-b border-gray-100' : ''}`}
                        onClick={() => set('classAssessment', value)}
                      >
                        <td className="px-3 py-2.5">
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="radio"
                              name="classAssessment"
                              value={value}
                              checked={classAssessment === value}
                              onChange={() => set('classAssessment', value)}
                              className="accent-brand-accent flex-shrink-0"
                            />
                            <span className={classAssessment === value ? 'font-medium text-brand-dark' : 'text-gray-700'}>
                              {value}
                            </span>
                          </label>
                        </td>
                        <td className="px-3 py-2.5 text-gray-500 text-xs">{blankDesc}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </fieldset>

        <div className="border-t border-gray-100 pt-4">
          <SectionLabel>Number of Problem Options to Generate</SectionLabel>
          <div className="flex items-center gap-3">
            <input
              type="number"
              min={1}
              max={10}
              value={numOptions}
              onChange={e => {
                const v = Math.min(10, Math.max(1, parseInt(e.target.value) || 1));
                set('numOptions', v);
              }}
              className="w-20 border border-gray-300 rounded-md px-3 py-2 text-sm text-center
                         focus:outline-none focus:ring-2 focus:ring-brand-accent"
            />
            <span className="text-xs text-gray-500">options (1–10, default 4)</span>
          </div>
        </div>
      </Card>

      {/* Disclosure */}
      <Card className="p-5">
        <div className="flex items-start gap-2 mb-3">
          <ShieldAlert size={16} className="text-amber-600 flex-shrink-0 mt-0.5" />
          <span className="text-sm font-semibold text-gray-700">Usage Conditions</span>
        </div>
        <div className="bg-[#FFF2CC] border border-amber-300 rounded-md p-4 space-y-3 text-xs text-gray-700 mb-4">
          <p className="text-xs text-gray-500 italic">
            By using this tool you acknowledge and accept the following:
          </p>
          {DISCLOSURE_TEXT.map(({ heading, body }) => (
            <div key={heading}>
              <span className="font-semibold">{heading} — </span>
              {body}
            </div>
          ))}
        </div>
        <label className="flex items-start gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={disclosureAccepted}
            onChange={e => set('disclosureAccepted', e.target.checked)}
            className="mt-0.5 accent-brand-accent"
          />
          <span className="text-sm text-gray-700">
            I have read and accept the above conditions.
          </span>
        </label>
      </Card>

      {/* Error */}
      {error && (
        <div className="rounded-lg border border-red-300 bg-[#FCE4D6] p-4 text-sm text-red-800">
          <strong>Error:</strong> {error}
        </div>
      )}

      {/* Submit */}
      <div className="flex justify-end">
        <Button
          variant="primary"
          size="lg"
          onClick={onGenerate}
          disabled={!canGenerate}
        >
          Generate {numOptions} Problem Option{numOptions !== 1 ? 's' : ''} →
        </Button>
      </div>
    </div>
  );
};

export default Stage0Input;
